apiVersion: v1
kind: Service
metadata:
  namespace: events-cdc
  name: events-cdc-service
  labels:
    app: events-cdc-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: events-cdc-service
