apiVersion: v1
kind: Service
metadata:
  name: events-postgres
  labels:
    app: events-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: events-postgres
