version: '3'
services:
  redis:
    image: redis:5.0.3
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.2.4
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/?utm_source=github&utm_medium=rmoff&utm_campaign=ty.community.con.rmoff-listeners&utm_term=rmoff-devx
      # https://www.confluent.io/blog/kafka-listeners-explained/
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  events-postgres:
    image: events-postgres:${buildVersion:-latest}
    hostname: events-postgres
    container_name: events-postgres
    build: ../../../../events-db/events-postgres/deployment/docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      USE_DB_ID: ${USE_DB_ID}
      USE_JSON_PAYLOAD_AND_HEADERS: ${USE_JSON_PAYLOAD_AND_HEADERS}
  events-cdc-service:
    image: events-cdc-service:${buildVersion:-latest}
    hostname: events-cdc-service
    container_name: events-cdc-service
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
      args:
        buildVersion: ${buildVersion}
    ports:
      - "8080:8080"
    links:
      - events-postgres
      - kafka
      - redis
      - zookeeper
    depends_on:
      - events-postgres
      - kafka
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EVENTS_CDC_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTS_CDC_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      EVENTS_CDC_READER_MYSQLREADER_TYPE: mysql-binlog
#      EVENTS_CDC_READER_MYSQLREADER_DATASOURCEURL: jdbc:mysql://events-mysql:3306/events
#      EVENTS_CDC_READER_MYSQLREADER_DATASOURCEUSERNAME: root
#      EVENTS_CDC_READER_MYSQLREADER_DATASOURCEPASSWORD: mysqladmin
#      EVENTS_CDC_READER_MYSQLREADER_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
#      EVENTS_CDC_READER_MYSQLREADER_LEADERSHIPLOCKPATH: /events/cdc/leader/mysql
#      EVENTS_CDC_READER_MYSQLREADER_CDCDBUSERNAME: root
#      EVENTS_CDC_READER_MYSQLREADER_CDCDBPASSWORD: mysqladmin
#      EVENTS_CDC_READER_MYSQLREADER_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
#      EVENTS_CDC_READER_MYSQLREADER_MYSQLBINLOGCLIENTUNIQUEID: 1234567890
#      EVENTS_CDC_READER_MYSQLREADER_OUTBOXID: 1
#      EVENTS_CDC_READER_MYSQLREADER_OFFSETSTOREKEY: MySqlBinlog

#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_TYPE: polling
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEURL: jdbc:postgresql://events-postgres:5432/postgres
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEUSERNAME: postgres
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEPASSWORD: postgres
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_OUTBOXID: 2
#      EVENTS_CDC_READER_POSTGRESPOLLINGREADER_LEADERSHIPLOCKPATH: /events/cdc/leader/postgres-polling

      EVENTS_CDC_READER_POSTGRESWALREADER_TYPE: postgres-wal
      EVENTS_CDC_READER_POSTGRESWALREADER_DATASOURCEURL: jdbc:postgresql://events-postgres:5432/postgres
      EVENTS_CDC_READER_POSTGRESWALREADER_DATASOURCEUSERNAME: postgres
      EVENTS_CDC_READER_POSTGRESWALREADER_DATASOURCEPASSWORD: postgres
      EVENTS_CDC_READER_POSTGRESWALREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTS_CDC_READER_POSTGRESWALREADER_OUTBOXID: 3
      EVENTS_CDC_READER_POSTGRESWALREADER_LEADERSHIPLOCKPATH: /events/cdc/leader/postgres

#      EVENTS_CDC_PIPELINE_P1_TYPE: event-sourcing
#      EVENTS_CDC_PIPELINE_P1_READER: MYSQLREADER
#
#      EVENTS_CDC_PIPELINE_P2_TYPE: event-sourcing
#      EVENTS_CDC_PIPELINE_P2_READER: POSTGRESPOLLINGREADER
#
#      EVENTS_CDC_PIPELINE_P3_TYPE: event-sourcing
#      EVENTS_CDC_PIPELINE_P3_READER: POSTGRESWALREADER

#      EVENTS_CDC_PIPELINE_P4_TYPE: transactional-messaging
#      EVENTS_CDC_PIPELINE_P4_READER: MYSQLREADER
#
#      EVENTS_CDC_PIPELINE_P5_TYPE: transactional-messaging
#      EVENTS_CDC_PIPELINE_P5_READER: POSTGRESPOLLINGREADER

      EVENTS_CDC_PIPELINE_EVENTS_TYPE: transactional-messaging
      EVENTS_CDC_PIPELINE_EVENTS_READER: POSTGRESWALREADER

#      EVENTS_CDC_CLEANER_C1_PIPELINE: P4
#      EVENTS_CDC_CLEANER_C1_PURGE_MESSAGESENABLED: "true"
#      EVENTS_CDC_CLEANER_C1_PURGE_MESSAGESMAXAGEINSECONDS: 1
#      EVENTS_CDC_CLEANER_C1_PURGE_INTERVALINSECONDS: 1
#
#      EVENTS_CDC_CLEANER_C2_PIPELINE: P5
#      EVENTS_CDC_CLEANER_C2_PURGE_MESSAGESENABLED: "true"
#      EVENTS_CDC_CLEANER_C2_PURGE_MESSAGESMAXAGEINSECONDS: 1
#      EVENTS_CDC_CLEANER_C2_PURGE_INTERVALINSECONDS: 1

#      EVENTS_CDC_CLEANER_C3_DATASOURCEURL: jdbc:postgresql://events-postgres:5432/postgres
#      EVENTS_CDC_CLEANER_C3_DATASOURCEUSERNAME: postgres
#      EVENTS_CDC_CLEANER_C3_DATASOURCEPASSWORD: postgres
#      EVENTS_CDC_CLEANER_C3_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
#      EVENTS_CDC_CLEANER_C3_PURGE_MESSAGESENABLED: "true"
#      EVENTS_CDC_CLEANER_C3_PURGE_MESSAGESMAXAGEINSECONDS: 1
#      EVENTS_CDC_CLEANER_C3_PURGE_INTERVALINSECONDS: 1
