@startuml
interface com.events.messaging.leadership.coordination.LeaderSelectorFactory {
~ LeaderSelector create(String,String,LeaderSelectedCallback,LeaderRemovedCallback)
}
interface com.events.messaging.leadership.coordination.LeaderSelector {
~ void start()
~ void stop()
}
interface com.events.messaging.leadership.coordination.LeaderRemovedCallback {
~ void run()
}
interface com.events.messaging.leadership.coordination.LeadershipController {
~ void stop()
}
interface com.events.messaging.leadership.coordination.LeaderSelectedCallback {
~ void run(LeadershipController)
}
@enduml