@startuml

hide members

interface PublishingFilter {}

PublishingFilter <|-- KafkaDuplicatePublishingDetector
PublishingFilter <|-- RabbitMQDuplicatePublishingDetector
PublishingFilter <|-- RedisDuplicatePublishingDetector
PublishingFilter <|-- ActiveMQDuplicatePublishingDetector

@enduml


